name: nortia
recipe: wordpress
config:
  php: '8.0'
  xdebug: true
  database: mariadb
  webroot: web
services:
  pma:
    type: phpmyadmin
    overrides:
      environment:
        PMA_USER: nortia
        PMA_PASSWORD: nortia
  database:
    creds:
      user: nortia
      password: nortia
      database: nortia
  nodejs:
    type: node:16
    globals:
      yarn: latest
tooling:
  yarn:
    service: nodejs
  npm:
    service: nodejs
  node:
    service: nodejs
